### ISSUE TITLE
I am not able to execute MAVGAnalysis on Java 1.8

### ISSUE THREAD

**Issue by Seeelefant** [ecmnet/MAVGCL#114]
Trying to execute MAVGCL leads to 
d:\MAVGCL\MAVGCL\dist>java -jar MAVGAnalysis.jar
Exception in thread "JavaFX Application Thread" Exception in thread "main" java.lang.UnsupportedClassVersionError: com/comino/mav/control/IMAVController has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)

d:\MAVGCL\MAVGCL\dist>java -version
java version "1.8.0_202"
Java(TM) SE Runtime Environment (build 1.8.0_202-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.202-b08, mixed mode)

A compile with the JDK 11.0.2 is not successful as the JavaFX libs are missing.

Please advice
--Seeelefant

**Comment by ecmnet** [comment]
As I am not using maven, to clear this issue automatically, you have to build [mavcomm.jar](
https://github.com/ecmnet/MAVComm) by your own.
